### ISSUE TITLE
[Dominic] API framework (add, delete, etc.) for storing a user's post data and the comments of the post

### ISSUE THREAD

**Issue by domph** [domph/p1-rain#20]
The data we'll store in our website includes account data (username, userid, hashed password), post data (who made the post, description, title, date, image data), and comment data (who made the comment, date, which post it belongs to). This ticket aims to establish the back-end structure for storing the data so that it can be used by other team members in the back-end code. The first ticket (account creation system) will have already covered the basic structure of the user, so this ticket aims to augment the work done there.

- [x] Post data methods/fields: each user object will have methods to add a new post
- [x] Comment data methods/fields: each post object will have methods to add a new comment

Basic flow: add new post --> construct a new post in a global database --> only add the id of the post to the user's list of posts; if a post is delete, it will need to be deleted from the global post database & the id will be removed from the user's list of post (ids)

Work completed by 5/21:
- Code links: (1) [Controller -- see post/comment sections; addPost, deletePost, addComment, deleteComment](https://github.com/domph/p1-rain/blob/main/src/main/java/rain/finalproject/picshare/web/UserController.java), (2) [Corresponding post/comment models, services, and repositories](https://github.com/domph/p1-rain/tree/main/src/main/java/rain/finalproject/picshare)
- [Commit](https://github.com/domph/p1-rain/commit/aeb5154f820a5e4c35ec3bdb26774c077b9f2d12)
- Note: This ticket is all about establishing the back-end framework to prepare for ticket #21  (the front end).

**Comment by domph** [comment]
Self-grade score: **3/3**

**Comment by banditcat12** [comment]
reviewed by sean

**Comment by jm1021** [comment]
Dominic, this is real nice.  I am wondering if on addPost and others if you think try catch should be used.  Is there possibility for you if's to fail and then you would need to gracefully handle error or redirect to error pages.   In any case, it seem like you are moving forward with key API technicals.  Nice job 3/3
