### ISSUE TITLE
[Dominic] Design front-end template for posts (title, description, date, comments, etc.) & connect to back-end

### ISSUE THREAD

**Issue by domph** [domph/p1-rain#21]
Posts will be displayed on a feed page for users to view all the photos ever posted, along with their respective title, description, date of posting, and comments. This ticket aims to create a thymeleaf fragment template (combining HTML, CSS) for what each post will look like. It also aims to connect the front-end to the back-end (thus allowing for the completion of post viewing, comment posting, and comment viewing).

- [x] Basic design of post (bootstrap card design)
- [x] Spots for the title, name, date, and image
- [x] A comment section (ideally comments will be limited to 2-3 before a "read more" section is introduced, which when pressed will expand the comment section)
- [X] Connect front-end UI to back-end endpoints, allowing for post viewing, post deleting, comment viewing, and comment posting/deleting

Work completed by 6/1:
- Tangibles: [Image feed](https://apcsa-rain.azurewebsites.net/feed)
- Code links: [UserController.java -- see /feed and /getpostimage/{id}](https://github.com/domph/p1-rain/blob/main/src/main/java/rain/finalproject/picshare/web/UserController.java), [feed.html](https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/PicShare/feed.html)
- [Initial commit (does not consist of bug fixes)](https://github.com/domph/p1-rain/commit/e98ae3ce242a2ffc435cd3d8c3f3f430e3f5c97d)

**Comment by andrewzpu** [comment]
Good, specific ticket. It looks like you have a good visualization of what your user interface will look like. I feel that this project is supposed to be more java-focused, so make sure that all the code is oriented around your java code.

**Comment by keviin0** [comment]
Good front end ideas for the user interface that acts as a good blueprint going forward.

**Comment by banditcat12** [comment]
i like how you have a paragraph explaining the overall structure then go into checkpoints, very clear and followable

**Comment by AndrewPhilipJoseph** [comment]
I think that these are good, completable ideas for the remaining week. I've done some work on a feed page so I could help out with that portion.

**Comment by Dragon0344** [comment]
I like what you're planning but it looks like it conflicts with my project?

**Comment by banditcat12** [comment]
the feed looks great, and it's very easy to use. perhaps it might be possible to have the user maintain their scroll position on the screen after commenting instead of going all the way back up, but I know we discussed this and it's harder than it appears

**Comment by AndrewPhilipJoseph** [comment]
I agree with Sean the feed UI is very well done. For the scroll position I think that we could use either a box containing a scrollable area, or separate the feed into pages with a certain amount of posts per page.
