### ISSUE TITLE
[Dominic] Design front-end for making posts & connect front-end to back-end

### ISSUE THREAD

**Issue by domph** [domph/p1-rain#29]
Ticket #20 dealt with the back-end framework for making posts. This ticket deals with building the front-end and bridging the two, allowing for complete functionality for making posts (displaying/viewing posts is a different ticket).

- [X] Create the HTML (using Boostrap) design for making posts (creating the form) & connecting it to Bootstrap
- [X] Connecting the form to the back-end (call the back-end endpoint)
- [X] Convert database entries for long strings (e.g. image data, comment data) to Clob types (since strings are capped at 255 characters)
- [X] Create a page for accessing pages that require being logged in --> page allows you to login

Work completed by 6/1:
- Tangibles: [/addpost (need to be logged in) -- access after logging in by clicking on your name --> "Make Post"](https://apcsa-rain.azurewebsites.net/addpost)
- Code links: [upload.html](https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/PicShare/upload.html), [Controller (scroll to mappings for /addpost)](https://github.com/domph/p1-rain/blob/main/src/main/java/rain/finalproject/picshare/web/UserController.java), [AccountRequired.html](https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/PicShare/AccountRequired.html)
- [Commit](https://github.com/domph/p1-rain/commit/59929b135477d64eb4f35d17d2a97d8a42b960e7)

**Comment by banditcat12** [comment]
looking good dominic! I liked how you wrote a long paragraph in the issue so we know the full story and functionality

**Comment by AndrewPhilipJoseph** [comment]
Nice progress, I think the detail in your tickets is very well done.

**Comment by Dragon0344** [comment]
I mean, it looks good, I just don't know the account information.
