### ISSUE TITLE
[Andrew] Design main page UI and connect the feed search options in HTML to controller

### ISSUE THREAD

**Issue by AndrewPhilipJoseph** [domph/p1-rain#31]
- [x] create HTML for the main page
- [x] create controller
- [ ] link controller, code and html (cannot currently do as post needs to be non-null to test functionality, otherwise HTML errors) 

* HTML               https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/Main/MainPageDemo.html
* Controller        https://github.com/domph/p1-rain/blob/main/src/main/java/rain/finalproject/picshare/web/FeedController.java
* Tangible           https://apcsa-rain.azurewebsites.net/MainPageDemo

**Comment by domph** [comment]
Nice progress -- might want to redesign some of the UI on the main page so that it fits the overall Bootstrap theme of the website (the search option buttons are a bit off, and the search button could be modified so that it has text/icon rather than being an empty button).

**Comment by AndrewPhilipJoseph** [comment]
I am satisfied with the progress that I have made on this, but it is still currently limited as I need posts to not be null so that I can run the commented out portions of code.

**Comment by banditcat12** [comment]
i like your detailed commit, but it's clear the html for the main page is just a prototype. The controller code looks promising and from viewing it, it was evident how it worked

**Comment by Dragon0344** [comment]
Nice checklist, but apparently the buttons don't quite work(I'm getting a HTTP status 405- Method not allowed every time I hit the Highest Rated button)
