### ISSUE TITLE
[Andrew] Modify all minilabs to fit theme

### ISSUE THREAD

**Issue by AndrewPhilipJoseph** [domph/p1-rain#34]
- [x] fix navigation
- [x] fix style
https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/LinkedList/LLAndrew.html
https://github.com/domph/p1-rain/blob/main/src/main/resources/templates/Sort/SortAndrew.html

**Comment by domph** [comment]
Definitely a big part of having a nice user experience is having a persistent navigation bar that allows you to not have to solely rely on the browser's back button, so making sure that the navigation bar is persistent across all your mini-labs is important (see Sean or my mini-labs, specifically the HTML part, for reference on how to do this). Our mini-labs also have Bootstrap components you can refer to, but here's a link if you want more options: https://getbootstrap.com/docs/4.6/getting-started/introduction/.

**Comment by AndrewPhilipJoseph** [comment]
I agree that this is important for the overall user experience. This ticket will probably be very easily completed however, so if I finish it too quickly I may try finding other things to occupy the rest of the time with.

**Comment by domph** [comment]
Some of the navbars on your various minilabs aren't functional -- did you perhaps forget to import a Bootstrap JS module? Also, some of the navbars are still missing, so I'd check those out. Overall, the next step appears to be redesigning the minilabs so that their themes are consistent with the other minilabs (check out mine and Sean's).

**Comment by banditcat12** [comment]
I don't see any bootstrap for any of your minilabs (well I see an attempt for the linked list one), and as Dominic says, the nav bar is not working when it should be persistent throughout the whole site. In the html document, make sure you use the thymeleaf fragemtents that were made for the nav bar and bootstrap js in general. Copying the style of either mine or dominics minilabs should be useful, it's how I redesigned mine.
