### ISSUE TITLE
Final Week

### ISSUE THREAD

**Issue by Dragon0344** [domph/p1-rain#36]
To do
Convert all minilabs to html(find out)
Finish all minilabs
-Completed:Binary Conversion, Inheritance
Need to fix: Sorting
Do: Linked Lists
https://replit.com/@Dragon0344/BinaryConverter#BinaryConverter.java
https://replit.com/@Dragon0344/ListSorting#Parent.java

**Comment by domph** [comment]
Currently having some errors running ListSorting (syntax errors); the binary conversion minilab highlights successful conversion of binary to decimal. Need to work on actually integrating it into the website (using Thymeleaf fragments, HTML, etc.). Also -- where's the inheritance lab (it's marked as complete but there's no code for it?)

**Comment by banditcat12** [comment]
I agree with dominic. A tangible should be on the website, not replit and there is little excuse at this point to not utilize thymeleaf, html, template controllers, etc this far in the tri.
